### ISSUE TITLE
The related custom fields in the wp_postmeta table are not displayed

### ISSUE THREAD

**Issue by tmamalio** [YMC-22/smart-filter#12]
When the Read More button is clicked to view more info on a post type, the associated custom fields are not displayed. Is there a way to include those fields in the following page and not just the title and description of the post type which are already displayed in the previous page?

**Comment by YMC-22** [comment]
Please clarify, custom fields are not displayed where: in a pop-up window when you click on the Read More button or in another place? Are you using a custom post layout or a standard one? Send a link to the page on your website where the filter plugin is installed. Describe your issue in more detail.

**Comment by YMC-22** [comment]
Thanks
