### ISSUE TITLE
typo in Add Custom Filter Layout. example:

### ISSUE THREAD

**Issue by jorge-teixeira** [YMC-22/smart-filter#14]
hello i think there is a typo in  Add Custom Filter Layout. example:

add_filter("ymc_filter_custom_layout_"14233_1, "callback_function", 10, 6);

the " in the wrong spot

add_filter("ymc_filter_custom_layout_14233_1", "callback_function", 10, 6);

**Comment by YMC-22** [comment]
Thanks.  We will check.

**Comment by YMC-22** [comment]
Thanks

**Comment by YMC-22** [comment]
Thanks
