### ISSUE TITLE
Dropdown filters

### ISSUE THREAD

**Issue by robpl1** [YMC-22/smart-filter#18]
My theme uses a blue background on the page with white text.

in YMC post Layouts > Enable Filters > Dropdown 
There are three selections in the Layouts area which are inconsistent in operation,
![filter](https://github.com/YMC-22/smart-filter/assets/39954642/44bfbfad-ca35-4c10-8a13-ded55c0a48f7)

Text: affects only items in the menu_passive, not menu-active. if you want to change the text colour for Category (in attached image) you need to use 
.filter-entry .dropdown-filter .menu-active{ color: black; background: white;}

Background only affects the background for text, not the container. The background is always black and cannot be changed.  According to the CSS inspector the element is at 
.ymc-smart-filter-container .filter-layout3 .dropdown-filter .menu-passive,
Changing background to any colour in the inspector changes the background as expected but when that CSS selector is use used the background does not change. 

Active text appears to have no effect on anything.

**Comment by YMC-22** [comment]
You can use custom styles to override plugin styles. In the future, we will revise the functionality for defining colors in the admin panel of the plugin. Thank you for your interest in the plugin.

**Comment by robpl1** [comment]
That's part of my problem. The styles, as identified by Google Inspector DON'T over-ride the the plugin styling. 
Google Inspector identifies the style for the dropdown menu container background as .ymc-smart-filter-container .filter-layout3 .dropdown-filter .menu-passive,
If you set the background colour in the Inspector it changes as required. However, when you add it to the WordPress Additional CSS it doesn't. Can you tell me what the element selector name is or how I can assign it a class?

**Comment by YMC-22** [comment]
Please send us a link to the page on your website where you do use our plugin

**Comment by robpl1** [comment]
https://themusicrealm.com
The dropdown in question is halfway down the page, Review Posts. Site is still in development

**Comment by YMC-22** [comment]
You can set the following rule with high priority in your styles using the !important keyword, for example:
.ymc-smart-filter-container .filter-layout3 .dropdown-filter .menu-passive { background: #ffffff !important; }
After this, your dropdown list background will be white. We hope this helps you.
![Screenshot_1](https://github.com/YMC-22/smart-filter/assets/110276757/23fcc408-a6ee-4296-9c2e-383b6553fd76)

**Comment by robpl1** [comment]
Thank you, that’s worked fine.
