### ISSUE TITLE
Clear search = show all?

### ISSUE THREAD

**Issue by DirkOlten** [YMC-22/smart-filter#2]
On my page https://flohheim.iwwerzwersch.de/flohheim-nord-2023-teilnehmerliste/ I just use the search function, which is working well.
My issue here is, when the searchfield ist cleared, I would expext to see all entries again as like before search.
Is there a way to have a button "reset search" to show all entries again?

Good and very powerful plugin. 
Thank you for sharing your work.
Greetings, Dirk

**Comment by YMC-22** [comment]
Hello Dirk Olten!
Thank you for reaching out to us for help. We will definitely take into account this issue and try to solve it in the near future. Expect a response.

**Comment by YMC-22** [comment]
Fixed the functionality of clearing the search result in the filter

**Comment by DirkOlten** [comment]
Wow, works like a charm.
This came just in time.
Thank you very much.
