### ISSUE TITLE
Filter for project not sorting

### ISSUE THREAD

**Issue by JonasCoach** [YMC-22/smart-filter#24]
Hi, I love the plugin, integrates really well with Divi.

Now I want to show a grid of projects under a special category, but I can't sort it. No matter what I do, after saving it reverts to the order the projects are sorted in WP.

I have tried all kinds of sorting and also manually sorted the projects under "Add posts".

Ideas?

**Comment by YMC-22** [comment]
Hi! 
Send a link to your website page. By what criteria do you want to sort posts?

**Comment by YMC-22** [comment]
Thanks
