### ISSUE TITLE
Validate WCAG 2.1 

### ISSUE THREAD

**Issue by jorge-teixeira** [YMC-22/smart-filter#26]
hello  i try to validate the WCAG 2.1 Accessibility  and it needs a define the **type="submit"** in button .

FILE: /includes/core/frontend/layouts/search/search-layout.php

```

            <button class="search-form__submit btn-submit" type="submit">
                <?php esc_html_e($ymc_search_text_button, 'ymc-smart-filter'); ?>
            </button>

```

WCAG 2.1 validator
https://accessmonitor.acessibilidade.gov.pt/

**Comment by YMC-22** [comment]
Fixed
