### ISSUE TITLE
Custom Theming breaks after latest update (2.9.22)

### ISSUE THREAD

**Issue by tpapaz** [YMC-22/smart-filter#28]
Hello guys, thanks again for the wonderful plugin,

It seems that after the latest update, my custom css theme that I wrote for the custom filtering does not work.

More specifically, for example the YMC CSS class selector ".ymc-smart-filter-container .container-posts .post-custom-layout .post-item"
loads first and ignores my custom ones that were working all this time.

-> It tries to load the classes from ".../wp-content/plugins/ymc-smart-filter/includes/assets/scss/style.scss".

Thanks!

**Comment by YMC-22** [comment]
Hi! 
Please send me a link to the page of a previous site where you use element styling. Perhaps your selector specification does not match the plugin specification.

**Comment by tpapaz** [comment]
Link:
https://bhv.iti.gr/publications/

It worked perfectly fine all this time before the update.
I put specific rules in my css: eg:
-> .ymc-filter-1274 .container-posts .post-custom-layout .post-item
 
but they get ignored now. I even try to set explicitly "ymc-smart-filter-container .container-posts .post-custom-layout .post-item" but it gets ignored.
See photo below:
![image](https://github.com/user-attachments/assets/4ce53452-d45a-41a8-805a-4991fbe69058)


I repeat, this started happening after the latest update.

**Comment by tpapaz** [comment]
Btw it tries to load a .scss file from the plugin

**Comment by YMC-22** [comment]
Thanks for waiting. Our specialists are working to resolve the error. There will be a plugin update today, please update!

**Comment by YMC-22** [comment]
We have fixed the bugs. Please update the plugin on your side.

**Comment by tpapaz** [comment]
Thanks for your immediate resolve of the issue.

Only one thing I see that remains. The font "Poppins" remains as default, even when I change it to Roboto from the YMC UI!

**Comment by tpapaz** [comment]
(Not everywhere, but in some cases!)
e.g.: https://bhv.iti.gr/projects/

**Comment by YMC-22** [comment]
Download the plugin from the WordPress repository and upload the entire plugin again to your site in the plugins folder via FTP. Most likely, not all files were uploaded to the repository) Update the files again!
