### ISSUE TITLE
Pulling styles from current theme?

### ISSUE THREAD

**Issue by fardeenxyz** [YMC-22/smart-filter#29]
Hey, thanks for this amazing plugin. It works great. 

Coming to the issue, I currently work exclusively with block themes and at most times (a combination of default theme + twentig plugin), I also use gutena forms and few other plugins which pull in default styles of my theme automatically. So, I don't have to worry about styling them, can this be done in your plugin? It would be a great addition and sites will look a lot cleaner and cohesive. 

Hope you consider this, thanks again for putting out such a great plugin for free.

**Comment by YMC-22** [comment]
Thanks for your feedback, we will definitely take this into account in future releases of the plugin
