### ISSUE TITLE
AND multiple selector

### ISSUE THREAD

**Issue by websuits** [YMC-22/smart-filter#3]
If i define a multiple selection filter, using 'AND' taxonomy relation, shouldn't selecting 2 categories or tags work like a conditional rendering and remove results that are not in CategoryA AND CategoryB in the same time? I expect OR to behave as default and show posts that are in CategoryA or in CategoryB, or both.

Example: I have post1 in category1, and post2 in category1 and category 2.  
Action: Multi select category1 and category2 both in front
Expected behaviour: Display only post 2 in results list

**Comment by YMC-22** [comment]
Hello, Stefan Luntraru!
Could you explain in more detail the essence of your task, which relates to the multiple selector filter. For a more detailed explanation, we need to clearly understand the essence of the task.

**Comment by websuits** [comment]
It's probably not a bug but something i would expect to work by default.

Taxonomy Relation has 2 options : AND and OR.

Taxonomy relation works between taxonomies, so in a multiple choice scenario filtering by tax1 AND tax2, i am able to exclude post1 that is in tax1, but is not in tax1 AND tax2 in the same time.

Having only 1 taxonomy (Categories) should work the same as between taxonomy terms (sub categories). For example with AND set, i should be able to filter by category1 and category 2, and exclude post1 that is in category1, but is not in category1 and category2 in the same time.

I hope this is more clear now.

**Comment by YMC-22** [comment]
The fact is that the entire logic of the filter plugin is determined by the peculiarities of the operation of the WP_Query class object in the WordPress core. The plugin itself uses all the parameters of this class and accordingly displays the result according to the previously passed parameters. We do not use any filters to override the logic of this object. For a more detailed understanding, please refer to the official documentation on using this class - https://developer.wordpress.org/reference/classes/wp_query
Our plugin completely imitates the work of WP_Query; this is equivalent to if you manually wrote the query itself and passed all the necessary parameters to this object.

**Comment by YMC-22** [comment]
We hope this helps
