### ISSUE TITLE
Does not support HTML

### ISSUE THREAD

**Issue by ApekshaShelar** [YMC-22/smart-filter#30]
I installed filter and grid plugin to filter my posts. And I need to add excerpt for individual posts But I want that excerpts in list form.
I tried every possible way to break the lines but nothing worked. No <br>tag, nor <p><div>tags. Nothing supporting.

Do this plugin support HTML? If not, Is there any way to solve my issue?

**Comment by YMC-22** [comment]
Hi! 
You can redefine the content structure of each filter card using the filter - add_filter('ymc_post_custom_layout_545_1', 'my_custom_post_layout', 10, 5); There you can implement the logic you need to implement the content output (see documentation on palgain)

**Comment by IllusionMini** [comment]
In which file I have to add this code?

**Comment by YMC-22** [comment]
you will need to add this filter code to the root of your theme file named functions.php
