### ISSUE TITLE
Misplaced Post Title in all Post Layouts except Vertical Timeline 

### ISSUE THREAD

**Issue by mrmurtazaabbasi** [YMC-22/smart-filter#32]
There is a glitch if titles of post cards, and all the post types has this issue, the title is misplaced to top left corner and not following the layout of the post card. I changed the type of title from `header` to `div`. I also saw that the general class names are used which can interfare with other elements, my suggestion would be the use specific naming convintion for class names to avoid conflict with other element.
![image](https://github.com/user-attachments/assets/d716e70f-f1f0-45c3-b9c3-97c2f8597c04)
I edited the most left element's element type from header to div and it is working.

**Comment by YMC-22** [comment]
Hi!
Thanks for your comments. We will take your recommendations into account in future releases of our plugin.
