### ISSUE TITLE
Filter and grid plugin doesn't remove/hide the restricted post

### ISSUE THREAD

**Issue by IllusionMini** [YMC-22/smart-filter#33]
My posts are coming through filter and grid plugin. Do this plugin supports third-party plugin like GeoTargetingWp?

I'm using the plugin GeoTargetingWP in my website. But I'm facing a issue regarding Posts.

I want to show particular posts in particular country or regions. There are options to select 'Show in' and 'Never show in'. When I select 'Never show in' and select particular country. The post contents get hide but the post containing the area/whitespace remains their as it is (looks like blank box without content).

Filter and grid plugin doesn't remove/hide the restricted post. Why?

**Comment by YMC-22** [comment]
The plugin works in its own context and does not take into account the work of third-party plugins (GeoTargetingWP)

**Comment by IllusionMini** [comment]
Okay. I solved the problem by creating multiple filters as per requirement.

One more thing I wanted to ask is that can I change only the price filter
layout. Now I'm using a scrolling dropdown filter layout but I want the
only price filter in range format. Is there any way to change a specific
filter? By using code or anything else?

**Comment by YMC-22** [comment]
The plugin does not currently support this type of filter. You can custom implement it using all the tools and API of our plugin.

**Comment by IllusionMini** [comment]
Okay. Thank you...
