### ISSUE TITLE
Feature Request: Truncate Post Excerpts at Line Break or End of First Block in Grid Layouts

### ISSUE THREAD

**Issue by MavropaliasG** [YMC-22/smart-filter#36]
Thank you for this great plugin, and offering a free way for us to have a post grid that the user can filter through category.

**Feature Summary:** I would like to request a feature enhancement where post excerpts in the grid layout automatically truncate at the first line break (`<br>`) or end of a block (e.g., `<p>`, `<h2>`)

**Current Behavior:**
Currently, the plugin trims post excerpts based on a word limit, which doesn’t account for the structure of the content. This results in truncated text that may break the flow of the excerpt and provide less meaningful context.

**Requested Behavior:**

- Detect and stop at the first line break: The plugin should recognize a `<br>` or other line break tags and stop the excerpt at that point.
- Fallback to end of first block: If no line break is found, the excerpt should end after the first complete block element (e.g., `<p>`, `<h2>`, etc.).
- No automatic ellipsis: There should be no automatic ... added at the end when truncating based on line breaks or block endings.

**Example:**
Given the following post content:
```
<p>A Guide For Austronauts</p>
<p>In this section, we will...</p>
```

The plugin should automatically detect the end of the first paragraph (`<p>`) and stop the excerpt there, displaying:
`A Guide For Austronauts`

Similarly, if there's a line break:

`<p>This is a summary.<br>Additional details follow...</p>`

The excerpt should truncate at the line break:

`This is a summary.`

**Suggested Implementation:**
A toggleable option in the plugin's Excerpt Settings that allows users to choose whether they want to stop excerpts at:
- At the first line break (`<br>`)
- The first block of content.
- Have an option to remove the automatic addition of ... at the end of the excerpt.

Thank you! This feature would greatly improve the flexibility of the grid layout for content-heavy sites.

**Comment by YMC-22** [comment]
Hi!
Thank you very much for your feedback on improving our plugin. We will take your wishes into account in future releases.
