### ISSUE TITLE
Feature Request: Option to Display Full-Sized Uncropped Featured Images in Layouts

### ISSUE THREAD

**Issue by MavropaliasG** [YMC-22/smart-filter#37]
Hello,

First, thank you for your excellent work on this plugin.

Currently, the plugin's post layouts automatically crop featured images, which is limiting in certain design contexts. While there are options to modify other aspects of the post display, there is no way to select the size or prevent the image from being cropped. This results in a less flexible design and forces users to override the image display using custom CSS, which can be unreliable depending on the layout and theme being used.
Request:

I would like to request a feature where users can select the image size or format (e.g., uncropped, thumbnail, medium, full) when configuring the post layout. This would allow for a greater level of customization and ensure the full image is displayed as intended without resorting to CSS overrides or custom code.

**Example Implementation:**

In the admin panel where post layouts are configured, adding a dropdown or checkbox to select the desired image size (similar to how WordPress media library handles it) would be ideal. This could include options like:

- Full-size (uncropped)
- Thumbnail
- Medium
- Large

Thank you for considering this feature request. It would greatly enhance the plugin's flexibility and usability.

**Comment by YMC-22** [comment]
Thanks for the recommendations, we will look into them.
