### ISSUE TITLE
Advanced query with multiple categories selected in query options

### ISSUE THREAD

**Issue by jjkommunikation** [YMC-22/smart-filter#38]
Hi, 

i have an issue with doing an advanced query in my filter, 

i want to do a date sort from an acf field on each selected category filter
im trying to do this in advanced query with following: post_type=events&posts_per_page=-1&meta_key=start_dato&orderby=meta_value_num&order=ASC&tax_query[0][taxonomy]=category&tax_query[0][field]=term_id&tax_query[0][terms]=7,9&tax_query[0][operator]=IN

but its doing this sort on every selected category in my frontend, 
i have also tried to do a "pre_get_posts" actions, maybe im overlooking something

![ymc_filter_and_grids_advanced_query](https://github.com/user-attachments/assets/1039634b-b555-4592-bd2c-20ae0cfc7736)

**Comment by YMC-22** [comment]
Hi!
You can use the query generator - https://crocoblock.com/freemium/tools/wp-query-generator/
Or we recommend you use another advanced query method - https://prnt.sc/UGsG9EEfls1P
There you will need to specify the required parameters of the ACF fields for the WP Query object.
