### ISSUE TITLE
Feature: Sort order by taxonomy

### ISSUE THREAD

**Issue by Triloworld** [YMC-22/smart-filter#4]
For Asc/desc order by clicking on taxonomy title in posts list.

Right now is only on posts data:
> 
> Usage example:
> List of fields for sorting posts: ID, author, title, name, date, modified, type, parent, rand, comment_count
> Important! Keep HTML structure with all attributes as in the example below.
> 

For example: Click taxonomy title in table header "Size of cloth" will sort posts by using that in asc/desc

**Comment by Triloworld** [comment]
There add "Taxonomy" and give option to list it as one button or headers that can be order (same function and look as "General" -> "Taxonomy")
Maybe multiple option but with taxonomy additional?
![Zrzut ekranu 2023-09-13 o 19 09 21](https://github.com/YMC-22/smart-filter/assets/2671726/e90228ba-e60d-4a4b-8ac3-13e3e57852ab)

**Comment by Triloworld** [comment]
Even to overcome that I don't have access to same option. I mean `custom sort layout` to do it in `functions.php`:
![Zrzut ekranu 2023-09-13 o 19 23 43](https://github.com/YMC-22/smart-filter/assets/2671726/251cb090-6229-4aa5-acd3-420ac8d42a0a)

**Comment by YMC-22** [comment]
Thanks for your suggestion. We will look at this functionality in the near future.
