### ISSUE TITLE
Feature Request: Link Customization and Element Positioning Control in Post Grid Layout

### ISSUE THREAD

**Issue by nirwaiz** [YMC-22/smart-filter#40]
First, thank you for developing such a versatile plugin for filtering and displaying posts! The functionality is robust and covers a wide range of use cases. I wanted to suggest two enhancements that would improve user experience and layout flexibility:

Direct Link Access for Post Titles and Images:
Currently, it seems that users can only navigate to the post by clicking the dedicated (Read More) button in each post grid item. Adding an option to make the post title and image clickable would improve accessibility and make navigation easier.

Control Over Post Element Placement:
Another enhancement would be to allow finer control over the positioning of post elements meta info (e.g., title, image, tags, excerpt) within the grid layout. Right now, it appears that these elements have a fixed placement, limiting layout customization. It would be great if we could control element positions

**Comment by YMC-22** [comment]
Hi!
Thanks for your recommendations on how to improve our plugin and we will take your wishes into account in the future. At the moment, to change the structure of post cards, there is a custom layout that allows you to create the desired content structure.
