### ISSUE TITLE
Terms Select 'ALL' not working when I add new term

### ISSUE THREAD

**Issue by franconiglio** [YMC-22/smart-filter#43]
Hi, I have a grid post based on a custom post type where I show the categories filter with the ALL selection.
When I add a new category it is not automatically shown. If I go to the grid post I see the 'ALL' selector deselected and the new category not selected.
I would like that when I add a new category this is automatically selected so with the 'ALL' parameter continuing to work.
The selected post sorting is DESC.
My plugin version is the latest 2.9.46
How can I achieve this goal?
Thanks so much in advance.

**Comment by YMC-22** [comment]
Hi!
When you add a new category to the post type, you will need to activate it manually in the filter admin panel (this is how the plugin is built). Then, you should select the desired tags and save all the settings. After that, the frontend will display a grid of posts with the selected tags.
