### ISSUE TITLE
Extending post-layout (text color, background color) to metadata (title)

### ISSUE THREAD

**Issue by principiante960** [YMC-22/smart-filter#44]
I selected white for the text and a dark green (#016a45) and I choose to display the title. However I am not able to display the change the color the title is displayed

**Comment by YMC-22** [comment]
Hi! You can custom CSS  override the elements of the post card using your own styles.

**Comment by principiante960** [comment]
Tks YMC-22 can you detail a little bit more since I am a beginner

**Comment by YMC-22** [comment]
Send a link to your website page with a detailed description of what you want to change.

**Comment by principiante960** [comment]
https://www.archidellastoria.it/almanacco/

If you scroll down you see posts under the filter. The posts are special ones, called Almanacco, created with ACF: Secure Custom Fields

The title of each Almanacco displays in black, while the text is in white and the background is in green. I would like to be able to change the color the title dispays in

**Comment by YMC-22** [comment]
you should change the header color using your custom styles, like this:
`.ymc-smart-filter-container .container-posts .post-layout2 .ymc-post-layout2 .title a {
     color: #ffffff !important;
}`

https://prnt.sc/w9Cz_218SsYE

Hope this helps you.

**Comment by principiante960** [comment]
Many, many thanks for your help

**Comment by YMC-22** [comment]
Good Luck!
