### ISSUE TITLE
Woocommerce product visibility not considered on products query

### ISSUE THREAD

**Issue by daudtivan** [YMC-22/smart-filter#45]
Woocommerce has an additional shop visibility attribute one can set at the product level to "search only" or "hidden".
Useful to "filter out" things without losing sales or product logs and history. Perfect fit for retired or deprecated items. 
![Seleção_002](https://github.com/user-attachments/assets/340f4599-7bd7-4f17-a852-f19895ab8bd9)

I've been playing with your plugin and noticed it's not considered on the query and **all items** are returned, no matter what's set at the product visibility level.

Can you pls take a look at that?
Tks and congrats for the good work.

**Comment by YMC-22** [comment]
Hi!
Our plugin does not yet work fully with Woocommerce. In the future, our plugin may be integrated into the functionality of Woocommerce. Thanks for using our plugin.
