### ISSUE TITLE
Help! Weird arrows and photo file info showing

### ISSUE THREAD

**Issue by Wiggy1095** [YMC-22/smart-filter#6]
![weird formatting](https://github.com/YMC-22/smart-filter/assets/149312158/838d373b-cd89-4dbf-b769-5c99223441aa)
Not sure why there are small arrows appear beside the categories, or why the filtered items have the photo upload and file information showing up.
Couldn't find where to edit or adjust these two things. 
Otherwise the plugin is perfect for what I need. I like that this style does not show date or author of the pages.

I am using this with Custom post type > Pages > Categories

**Comment by Wiggy1095** [comment]
Figured out the photo file info... Our pages have a photo gallery at the top of the page, so it is showing the file info for those images. It would be good to have a brief description of each filtered page instead, but alternately an option to just include the featured image and title that hyperlinks to the page would work great as well if that is possible. The arrows are still weird though.

**Comment by YMC-22** [comment]
Hello!
Provide us with a link to the page of the site where you use the filter so that we can analyze the current issues.

**Comment by Wiggy1095** [comment]
Hello,

My site is currently in development so there is no public link I can provide you with unfortunately.

Let me know any info I can provide you with that might be helpful.

I looked at a few other plugins and another one I tried had the same issue with the small arrow appearing with the filter categories.


Marena Wigmore | Wolf Centre & Yours Outdoors Coordinator



Haliburton Forest & Wild Life Reserve Ltd.

1305 Redkenn Road | Haliburton, Ontario | K0M 1S0

P. 1-800-631-2198

E. ***@***.***



[cid:90975286-6d81-469e-9e53-0e322a72cb1d]<http://www.haliburtonforest.com/>



________________________________

**Comment by YMC-22** [comment]
It’s difficult for us to say what the issue might be, but we suspect that this is not caused by our plugin, but perhaps by other sources (theme, plugins, styles, etc.). In order to clearly determine the issue, you need to inspect the code of your page.
