### ISSUE TITLE
tried to change the color and text of post button "Read More", but not sure how to use the provided samples.

### ISSUE THREAD

**Issue by johocen168** [YMC-22/smart-filter#7]
Thanks for the nice plugin, it is easy to use and exactly what we need. but it's a pitty that can not change the color and text of post button easily.

copied the code you provided in "Example Custom Post Layout"  but it seems every post has a different id number, please see the screenshot and help me with the code, thanks
![shot_231230_231412](https://github.com/YMC-22/smart-filter/assets/119094358/1a9ea3c7-85ed-4297-966f-65f3bef7de6a)

function my_custom_post_layout($layout, $post_id, $filter_id, $increment_post, $arrOptions) {  
   $layout  = '<h2>'.get_the_title($post_id).'</h2>';
   $layout .= '<p>'.wp_trim_words(get_the_content($post_id), 30).'</p>';
   $layout .= '<a href="'.get_the_permalink($post_id).'">Read More</a>'; 
   // $layout .= '<a class="'.esc_attr($arrOptions['class_popup']).'" data-postid="'.esc_attr($post_id).'" href="#">Open Popup</a>';  
   return $layout;
}
add_filter('ymc_post_custom_layout_545_1', 'my_custom_post_layout', 10, 5);

**Comment by YMC-22** [comment]
Hello! 
You will need to use a filter ID called 51502-1
Thus the name of the filter will be as follows:
add_filter('ymc_post_custom_layout_51502_1', 'my_custom_post_layout', 10, 5);
We hope this helps you.
![Clipboard01](https://github.com/YMC-22/smart-filter/assets/110276757/fce780e2-9c9c-4aa6-910f-77776e5b1a9b)

**Comment by YMC-22** [comment]
We hope this helps you.

**Comment by johocen168** [comment]
Sorry for late response, I was away from home.

I was confused, the short code is [ymc_filter id='51502'] 

I used the plugin "Snippet" to add the code as following, but didn't work, how can I make it right?

`function my_custom_post_layout($layout, $post_id=51446, $filter_id=51502_1, $increment_post, $arrOptions) {  
   $layout  = '<h2>'.get_the_title($post_id=51446).'</h2>';
   $layout .= '<p>'.wp_trim_words(get_the_content($post_id=51446), 30).'</p>';
   $layout .= '<a href="'.get_the_permalink($post_id=51446).'">Read333More</a>'; 
   // $layout .= '<a class="'.esc_attr($arrOptions['class_popup']).'" data-postid="'.esc_attr($post_id).'" href="#">Open Popup</a>';  
   return $layout;
}
add_filter('ymc_post_custom_layout_51502_1', 'my_custom_post_layout', 10, 5);`
