### ISSUE TITLE
$post_id in custom popup is not retrieved

### ISSUE THREAD

**Issue by yazeer-afk** [YMC-22/smart-filter#9]
I made a custom popup layout but the $post_id given provided from the custom post layout is not retrieved.

### Example:
This is the custom post layout `3820 is the $post_id`
![image](https://github.com/YMC-22/smart-filter/assets/59116882/182760f9-08f7-4373-a5be-0789082e1901)

And this is the popup layout `0 should have the $post_id printed`
![image](https://github.com/YMC-22/smart-filter/assets/59116882/a2a74df8-f0a6-4970-ad29-6244972f73cd)

### Code
code for the post layout
```
function custom_post_layout($layout, $post_id, $filter_id, $increment_post, $arrOptions) {  
?>
<style>
	.custom-post-container img {
		border-radius: 15px;
    	height: 23rem;
    	width: 100%;
    	object-fit: cover;
	}
	
	.custom-post-container:hover {
		scale: 1.02;
	}
</style>
<?php
	$post_content = get_the_content($post_id);
	$img_pattern = '/<figure class="wp-block-image">(.+?)<\/figure>/s';
	$subtitle_pattern = '/<!--\s*wp:heading\s*{"level":3}\s*-->(.*?)<!--\s*\/wp:heading\s*-->/s';
	
	preg_match($img_pattern, $post_content, $imgSearch);
	preg_match($subtitle_pattern, $post_content, $subtitleSearch);
	
	$img = $imgSearch[1];
	$subtitle = $subtitleSearch[1];
	
	// Layout -------------------------
	$layout = '<div class="custom-post-container" style="transition: all 0.2s linear;">';
	$layout .= '<a class="'.esc_attr($arrOptions['class_popup']).'" data-postid="'.esc_attr($post_id).'" href="#">';
	if($img !== null){
		$layout .= $img;
	}
	$layout  .= '<h2 style="text-decoration: none;">'.get_the_title($post_id).$post_id.'</h2>';
	if($subtitle !== null){
		$layout .= $subtitle;
	}
	$layout .= '</a></div>';

   return $layout;
}
add_filter('ymc_post_custom_layout_5073_1', 'custom_post_layout', 10, 5);
```

code for the popup layout
```
function custom_popup($layout, $post_id){
	$title = get_the_title($post_id);

	$layout = '<h2>Custom Text:'.esc_attr($post_id).' </h2>';
	return $layout;
}
add_filter('ymc_popup_custom_layout_5073_1', 'custom_popup', 10, 2);
```

**Comment by YMC-22** [comment]
send a link to the page on your website where the post filter is located, please

**Comment by yazeer-afk** [comment]
Thank you for the quick response!

Unfortunately, the staging environment where the problem popped up is password protected by my workplace so I'm unable to share access credentials or provide direct access to the environment.

However, I'm more than happy to collaborate and provide any additional information, logs, or screenshots that could help diagnose and address the issue effectively. Please let me know how else I can assist within these constraints.

**Comment by YMC-22** [comment]
Try manually adding a class called - ymc-popup - to the link (a tag). It’s not very convenient to say something without seeing the site live) 
https://prnt.sc/_xlbmNZE0sHj

**Comment by YMC-22** [comment]
https://prnt.sc/6E0TqtYmlT99
Remove nesting inside the link tag. There you have the heading H2 inserted into tag A. Look at the screenshot!!!
And check the closing tags carefully!!!

**Comment by yazeer-afk** [comment]
Yes this fixes it thank you very much!
However, the expected implementation was to have all the content inside the <a> tag so the modal would open up when the user clicks wherever on the post card. Ill find way

**Comment by YMC-22** [comment]
We has updated the plugin! Now you can do nesting of tags) Everything works correctly now!
